### ISSUE TITLE
suggest to replace general "host of" with more specific "parasitized by" 

### ISSUE THREAD

**Issue by jhpoelen** [millerse/A-Host-parasite-Catalog-of-North-American-Tachinidae-Diptera-#1]
Hi @millerse  - I just glanced at this beautiful dataset you've made machine readable. . . and I noticed that you used a somewhat highlevel symbiotic interaction type "host of" (RO:0002453) to describe the host of a parasite. Suggest to use the more specific "parasitized by" (RO:0002445).

**Comment by millerse** [comment]
Sorry about this one too.  Thanks for the catch.

**Comment by jhpoelen** [comment]
@millerse thanks for the quick response. Please close this issue after you resolve it.
